import type { Uuid } from '../entities.js';
import type { Employee } from './Employee.js';
import type { WorkforceTaskInstance } from './tasks.js';

export type WorkforceWarningSeverity = 'info' | 'warning' | 'critical';

/**
 * Represents a workforce-related alert generated by the scheduling pipeline.
 */
export interface WorkforceWarning {
  /** Simulation tick (hour) when the warning was generated. */
  readonly simTimeHours: number;
  /** Machine readable code describing the warning type. */
  readonly code: string;
  /** Human readable warning message for dashboards and logs. */
  readonly message: string;
  /** Severity flag guiding how the UI surfaces the warning. */
  readonly severity: WorkforceWarningSeverity;
  /** Optional structure affected by the warning. */
  readonly structureId?: Uuid;
  /** Optional employee related to the warning (e.g. overtime trend). */
  readonly employeeId?: Employee['id'];
  /** Optional task instance that triggered the warning. */
  readonly taskId?: WorkforceTaskInstance['id'];
  /** Free-form payload with additional deterministic metadata. */
  readonly metadata?: Record<string, unknown>;
}
