name: CI

on:
  push:
    branches:
      - main
      - feat/**
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore Vite build cache
        uses: actions/cache@v4
        with:
          path: |
            packages/ui/node_modules/.vite
            packages/ui/dist
          key: ${{ runner.os }}-vite-${{ hashFiles('pnpm-lock.yaml', 'packages/ui/package.json', 'packages/ui/vite.config.*') }}
          restore-keys: |
            ${{ runner.os }}-vite-

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Contract tests
        run: pnpm --filter @wb/facade test:contract

  perf-budget:
    runs-on: ubuntu-latest
    needs:
      - quality
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Enforce engine performance budget
        run: pnpm perf:ci
